#include <stdio.h>

// Go language keywords
// TODO include types
#define KEYWORD_BREAK 300
#define KEYWORD_DEFAULT 301
#define KEYWORD_FUNC 302
#define KEYWORD_INTERFACE 303
#define KEYWORD_SELECT 304
#define KEYWORD_CASE 305
#define KEYWORD_DEFER 306
#define KEYWORD_GO 307
#define KEYWORD_MAP 308
#define KEYWORD_STRUCT 309
#define KEYWORD_CHAN 310
#define KEYWORD_ELSE 311
#define KEYWORD_GOTO 312
#define KEYWORD_PACKAGE 313
#define KEYWORD_SWITCH 314
#define KEYWORD_CONST 315
#define KEYWORD_FALLTHROUGH 316
#define KEYWORD_IF 317
#define KEYWORD_RANGE 318
#define KEYWORD_TYPE 319
#define KEYWORD_CONTINUE 320
#define KEYWORD_FOR 321
#define KEYWORD_IMPORT 322
#define KEYWORD_RETURN 323
#define KEYWORD_VAR 324

// Go language operators and punctuation
#define PUNCTUATION_ADD 400
#define PUNCTUATION_SUBTRACT 401
#define PUNCTUATION_PRODUCT 402
#define PUNCTUATION_COCIENT 403
#define PUNCTUATION_MODULUS 404
#define PUNCTUATION_BITWISE_AND 405
#define PUNCTUATION_BITWISE_OR 406
#define PUNCTUATION_BITWISE_XOR 407
#define PUNCTUATION_LEFT_SHIFT 408
#define PUNCTUATION_RIGHT_SHIFT 409
#define PUNCTUATION_BIT_CLEAR 410
#define PUNCTUATION_UNARY_ADD 411
#define PUNCTUATION_UNARY_SUBTRACT 412
#define PUNCTUATION_UNARY_PRODUCT 413
#define PUNCTUATION_UNARY_COCIENT 414
#define PUNCTUATION_UNARY_MODULUS 415
#define PUNCTUATION_UNARY_BITWISE_AND 416
#define PUNCTUATION_UNARY_BITWISE_OR 417
#define PUNCTUATION_UNARY_BITWISE_XOR 418
#define PUNCTUATION_UNARY_LEFT_SHIFT 419
#define PUNCTUATION_UNARY_RIGHT_SHIFT 420
#define PUNCTUATION_UNARY_BIT_CLEAR 421
#define PUNCTUATION_AND 422
#define PUNCTUATION_OR 423
#define PUNCTUATION_RECEIVE 424
#define PUNCTUATION_INCREMENT 425
#define PUNCTUATION_DECREMENT 426
#define PUNCTUATION_EQUAL 427
#define PUNCTUATION_LESS_THAN 428
#define PUNCTUATION_GREATER_THAN 429
#define PUNCTUATION_ASSIGN 430
#define PUNCTUATION_NOT 431
#define PUNCTUATION_NOT_EQUAL 432
#define PUNCTUATION_LESS_EQUAL_THAN 433
#define PUNCTUATION_GREATER_EQUAL_THAN 434
#define PUNCTUATION_DECLARATION_ASSIGNMENT 435
#define PUNCTUATION_VARARGS 436
#define PUNCTUATION_PARENTHESES_START 437
#define PUNCTUATION_BRACKET_START 438
#define PUNCTUATION_BRACELET_START 439
#define PUNCTUATION_COMMA 440
#define PUNCTUATION_DOT 441
#define PUNCTUATION_PARENTHESES_END 442
#define PUNCTUATION_BRACKET_END 443
#define PUNCTUATION_BRACELET_END 444
#define PUNCTUATION_SEMICOLON 445
#define PUNCTUATION_COLON 446

// Go language tokens
#define TOKEN_IDENTIFIER 500
#define TOKEN_BOOLEAN_TRUE 501
#define TOKEN_BOOLEAN_FALSE 502
#define TOKEN_INTEGER_LITERAL 503
#define TOKEN_FLOATING_POINT_LITERAL 504
#define TOKEN_IMAGINARY_LITERAL 505
#define TOKEN_RUNE_LITERAL 506
#define TOKEN_STRING_LITERAL 507
#define TOKEN_COMMENT 508
#define TOKEN_BLANK 509

// Other constants
#define BLOCK_SIZE_BYTES 48
#define ERROR_CODE (-100)
#define TOKEN_NOT_FOUND (-101)
#define MAXIMUM_OPERATOR_LENGTH 3

#define OPERATORS_DB_PATH ../db/operators.db

// Custom types
typedef int SymbolsTableValue;